# Generated by Django 2.2.12 on 2020-05-11 16:52

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_email_sent',
            field=models.BooleanField(default=False, verbose_name='Onboarding Email Sent'),
        ),
    ]
