"""
Imports everything from base.py

Use this for project specific settings.

NOTE: This file should only be updated in a project specific project, not from DCC.
"""

import environ
from .base import *

ENV = environ.Env()

# Setup support for proxy headers
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

MODEL_API_BASE_URL = ENV('MODEL_API_BASE_URL',
                         default='http://localhost:5000/')
MODEL_API_SUBPATH = ENV('MODEL_API_SUBPATH', default='/model/')
MODEL_API_START = ENV('MODEL_API_RESULTS',
                      default='api/v3/prediction/?')
MODEL_API_STATUS = ENV('MODEL_API_RESULTS',
                       default='api/v3/prediction_status/?')
COVID_API_SIMULATIONS = ENV('COVID_API_SIMULATIONS',
                            default='/covid/api/simulations/')
MODEL_API_STATE = ENV('MODEL_API_STATE', default='Nebraska')
MODEL_API_STATE_ABBREVIATION = ENV(
    'MODEL_API_STATE_ABBREVIATION', default='NE')
MODEL_API_COUNTRY = ENV('MODEL_API_COUNTRY', default='US')

API_DEFAULT_COUNTIES = ENV.list(
    'DJANGO_API_DEFAULT_COUNTIES', default=['Lincoln'])
API_DEFAULT_MAP_X_COORD = ENV('DJANGO_API_DEFAULT_MAP_X_COORD', default='41.5')
API_DEFAULT_MAP_Y_COORD = ENV(
    'DJANGO_API_DEFAULT_MAP_Y_COORD', default='-100.0')
API_DEFAULT_MAP_ZOOM_LEVEL = ENV.int(
    'DJANGO_API_DEFAULT_MAP_ZOOM_LEVEL', default=3)
API_DEFAULT_SHELTER_DATE = ENV.str(
    'DJANGO_API_DEFAULT_SHELTER_DATE', default='2020-04-03')
API_DEFAULT_SHELTER_RELEASE_START_DATE = ENV.str(
    'DJANGO_API_DEFAULT_SHELTER_RELEASE_START_DATE', default='2020-06-01')
API_DEFAULT_SHELTER_RELEASE_END_DATE = ENV.str(
    'DJANGO_API_DEFAULT_SHELTER_RELEASE_END_DATE', default='2020-09-01')
API_DEFAULT_SIM_LENGTH = ENV.int('DJANGO_API_DEFAULT_SIM_LENGTH', default=56)
API_DEFAULT_SOCIAL_DISTANCING = ENV.bool(
    'DJANGO_API_DEFAULT_SOCIAL_DISTANCING', default=False)
API_DEFAULT_SOCIAL_DISTANCING_END_DATE = ENV.str(
    'DJANGO_API_DEFAULT_SOCIAL_DISTANCING_END_DATE', default='2020-09-01')
API_DEFAULT_QUARANTINE_START_DATE = ENV.str(
    'DJANGO_API_DEFAULT_QUARANTINE_START_DATE', default='2020-09-01')
API_DEFAULT_QUARANTINE_PERCENT = ENV.int(
    'DJANGO_API_DEFAULT_QUARANTINE_PERCENT', default=0)
API_DEFAULT_HIGH_RISK_QUARANTINE_PERCENT = ENV.int(
    'DJANGO_API_DEFAULT_HIGH_RISK_QUARANTINE_PERCENT', default=0)
API_DEFAULT_NDRAWS = ENV.int('DJANGO_API_DEFAULT_NDRAWS', default=50000)
API_DEFAULT_STATE = ENV.str('DJANGO_API_DEFAULT_STATE', default='Florida')

AWS_ACCESS_KEY_ID = ENV.str('AWS_ACCESS_KEY_ID', default='')
AWS_SECRET_ACCESS_KEY_ID = ENV.str('AWS_SECRET_ACCESS_KEY_ID', default='')
AWS_STORAGE_BUCKET_NAME = ENV.str('AWS_STORAGE_BUCKET_NAME', default='')
AWS_REGION_NAME = ENV.str('AWS_REGION_NAME', default='')

MEDIA_ROOT = 'app/'
MEDIA_URL = '/'
