# Generated by Django 2.2.12 on 2020-05-18 03:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_simulationrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationrun',
            name='model_input',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
