# Generated by Django 2.2.12 on 2020-05-18 03:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_auto_20200517_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationrun',
            name='webhook_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Webhook Token'),
        ),
    ]
