# Generated by Django 2.2.14 on 2020-07-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_auto_20200612_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='hash_files/')),
            ],
            options={
                'verbose_name': 'Hash File',
                'verbose_name_plural': 'Hash Files',
            },
        ),
    ]
