# Generated by Django 2.2.12 on 2020-06-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_auto_20200612_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='social_distancing',
            field=models.BooleanField(default=False, verbose_name='Social Distancing'),
        ),
    ]
