# Generated by Django 2.2.12 on 2020-05-28 02:34

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_simulationrun_webhook_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationrun',
            name='model_input',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='default_counties',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80, verbose_name='County Name'), help_text='Default Counties', size=8),
        ),
    ]
