# Generated by Django 2.2.13 on 2020-06-23 19:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_update_social_distancing_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='default_counties',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80, verbose_name='County Name'), help_text='Default Counties', size=16),
        ),
    ]
