# Generated by Django 2.2.12 on 2020-06-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0005_auto_20200527_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_value', models.CharField(max_length=40, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'Hash Value',
                'verbose_name_plural': 'Hash Values',
            },
        ),
    ]
