# Generated by Django 2.2.14 on 2020-07-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_hashfile'),
        ('covid', '0005_increase_max_default_counties'),
    ]

    operations = [
    ]
