# Generated by Django 2.2.12 on 2020-07-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0006_merge_20200713_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashvalue',
            name='timeseries_confirmed',
            field=models.FileField(null=True, upload_to='jh_data/%Y/%m/%d/', verbose_name='Confirmed JH Timeseries'),
        ),
        migrations.AddField(
            model_name='hashvalue',
            name='timeseries_deaths',
            field=models.FileField(null=True, upload_to='jh_data/%Y/%m/%d/', verbose_name='Deaths JH Timeseries'),
        ),
    ]
