# Generated by Django 2.2.13 on 2020-06-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0006_hashvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashvalue',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Timestamp'),
        ),
    ]
