# Generated by Django 2.2.13 on 2020-06-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0007_auto_20200611_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationrun',
            name='capacity_provider',
            field=models.CharField(max_length=8, null=True, verbose_name='Capacity Provider'),
        ),
    ]
