# Generated by Django 2.2.13 on 2020-06-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0008_simulationrun_capacity_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationrun',
            name='capacity_provider',
            field=models.CharField(max_length=12, null=True, verbose_name='Capacity Provider'),
        ),
    ]
